<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SNMPDATA [
	<!ELEMENT SNMPDATA (ATTRSET+)>
	<!ELEMENT ATTRSET (ATTRINFO+)>
	<!ATTLIST ATTRSET
	platform (all | windows | unix | nt | win2k | linux | solaris | hpux | aix | nt4 | unixA2 | winA3) #REQUIRED
>
	<!ELEMENT ATTRINFO (OID, ATTRNAME, ATTRTYPE, ATTRCOMPUTATION, ATTRDEPENDSON?)>
	<!ELEMENT OID (OIDNAME, OIDINDEX*)>
	<!ATTLIST OID
	representedby (value | string) #REQUIRED
		type (scalar | columnar) #REQUIRED
		returns (number | string | kb | bytes | mb) #REQUIRED
>
	<!ELEMENT ATTRNAME (#PCDATA)>
	<!ELEMENT ATTRTYPE (#PCDATA)>
	<!ELEMENT ATTRCOMPUTATION (#PCDATA)>
	<!ELEMENT ATTRDEPENDSON (OID+)>
	<!ELEMENT OIDNAME (#PCDATA)>
	<!ELEMENT OIDINDEX (OIDINDEXNAME, OIDINDEXNUM)>
	<!ATTLIST OIDINDEX
	type (string | number) #REQUIRED
>
	<!ELEMENT OIDINDEXNAME (#PCDATA)>
	<!ELEMENT OIDINDEXNUM (#PCDATA)>
]>
<SNMPDATA>
	<ATTRSET platform="unix">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="kb">
				<OIDNAME>1.3.6.1.4.1.791.2.9.4.5.2.9.2.1.17</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_ARGS</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>4</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROC_SZ</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> TOMB </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.9.4.5.2.9.2.1.22</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_ARGS</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>4</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME> PROC_CPU</ATTRNAME>
			<ATTRTYPE> STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.9.4.5.2.9.2.1.7</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_ARGS</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>4</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROCESS_INSTANCES</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.9.4.5.2.9.2.1.11</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_ARGS</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>4</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROC_STATUS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	</ATTRSET>
	<ATTRSET platform="nt">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.9.2.2.3.5.2.6</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROCESS_INSTANCES</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.9.2.2.3.5.2.10</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>TOT_THREADS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.9.2.2.3.5.2.3</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROC_STATUS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	</ATTRSET>
	<ATTRSET platform="win2k">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.43.2.10.2.1.31</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME> PROC_CPU</ATTRNAME>
			<ATTRTYPE> STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.43.2.10.2.1.9</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROCESS_INSTANCES</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.43.2.10.2.1.21</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>TOT_THREADS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.43.2.10.2.1.13</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROC_STATUS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	</ATTRSET>
	<ATTRSET platform="nt4">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.52.2.7.2.1.9</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROCESS_INSTANCES</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.52.2.7.2.1.15</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>TOT_THREADS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.52.2.7.2.1.8</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROC_STATUS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="kb">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.52.2.7.2.1.20</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROC_SZ</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> TOMB </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="kb">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.52.2.7.2.1.25</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_PATH</OIDINDEXNAME>
					<OIDINDEXNUM>2</OIDINDEXNUM>
				</OIDINDEX>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_USR</OIDINDEXNAME>
					<OIDINDEXNUM>3</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME> PROC_CPU</ATTRNAME>
			<ATTRTYPE> STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	</ATTRSET>
 <ATTRSET platform="unixA2">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="kb">
				<OIDNAME> 1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.35</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROC_SZ</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> TOMB </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME> 1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.14</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROCESS_INSTANCES</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.18</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROC_STATUS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	    <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.3</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROCNAME</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.7</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>EVAL_POLICY</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.2</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MATCH_TYPE</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
	<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.13</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>CLUSTER_TYPE</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.51</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>CPU_INTERVAL</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.41</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>CPU_INTERVAL_SHORT</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.53</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MAX_CPU_LONG</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> PERCENT </ATTRCOMPUTATION>
            <ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="string">
					<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.51</OIDNAME>
					<OIDINDEX type="string">
						<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.52</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MIN_CPU_LONG</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> PERCENT</ATTRCOMPUTATION>
            <ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="string">
					<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.51</OIDNAME>
					<OIDINDEX type="string">
						<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.43</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MAX_CPU_SHORT</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> PERCENT </ATTRCOMPUTATION>
            <ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="string">
					<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.41</OIDNAME>
					<OIDINDEX type="string">
						<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.42</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MIN_CPU_SHORT</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> PERCENT </ATTRCOMPUTATION>
            <ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="string">
					<OIDNAME>1.3.6.1.4.1.791.2.10.2.74.2.13.2.1.41</OIDNAME>
					<OIDINDEX type="string">
						<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
   </ATTRINFO>
</ATTRSET>
<ATTRSET platform="winA3">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>  1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.13</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				</OID>
			<ATTRNAME>PROCESS_INSTANCES</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>    1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.17</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
				</OID>
			<ATTRNAME>PROC_STATUS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	    <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.3</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROCNAME</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	    <ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.7</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>EVAL_POLICY</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.2</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MATCH_TYPE</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
	<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.12</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>CLUSTER_TYPE</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.28</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>CPU_INTERVAL</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.38</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MISC_MODE</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.30</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MAX_CPU_LONG</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> PERCENT </ATTRCOMPUTATION>
            <ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="string">
					<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.28</OIDNAME>
					<OIDINDEX type="string">
						<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.29</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MIN_CPU_LONG</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> PERCENT </ATTRCOMPUTATION>
            <ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="string">
					<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.28</OIDNAME>
					<OIDINDEX type="string">
						<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.40</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MAX_MISCVALUE</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
   <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME>1.3.6.1.4.1.791.2.10.2.90.2.11.2.1.39</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>PROC_NAME</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MIN_MISCVALUE</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
   </ATTRINFO>
</ATTRSET>
</SNMPDATA>
