<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SNMPDATA [
        <!ELEMENT SNMPDATA (ATTRSET+)>
        <!ELEMENT ATTRSET (ATTRINFO+)>
        <!ATTLIST ATTRSET
        platform (all | windows | unix | nt | win2k | linux | solaris | hpux | aix | nt4) #REQUIRED
>
        <!ELEMENT ATTRINFO (OID, ATTRNAME, ATTRTYPE, ATTRCOMPUTATION, ATTRDEPENDSON?)>
        <!ELEMENT OID (OIDNAME, OIDINDEX*)>
        <!ATTLIST OID
        representedby (value | string) #REQUIRED
                type (scalar | columnar) #REQUIRED
                returns (number | string | kb | bytes | mb | pages) #REQUIRED
>
        <!ELEMENT ATTRNAME (#PCDATA)>
        <!ELEMENT ATTRTYPE (#PCDATA)>
        <!ELEMENT ATTRCOMPUTATION (#PCDATA)>
        <!ELEMENT ATTRDEPENDSON (OID+)>
        <!ELEMENT OIDNAME (#PCDATA)>
        <!ELEMENT OIDINDEX (OIDINDEXNAME, OIDINDEXNUM)>
        <!ATTLIST OIDINDEX type (string | number) #REQUIRED >
        <!ATTLIST OIDINDEX inputType (asis | fromInput) "fromInput">
        <!ELEMENT OIDINDEXNAME (#PCDATA)>
        <!ELEMENT OIDINDEXNUM (#PCDATA)>
]>
<SNMPDATA>
	<ATTRSET platform="unix">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="%">
				<OIDNAME>1.3.6.1.4.1.94.1.21.1.7.1.0</OIDNAME>
			</OID>
			<ATTRNAME>CPUUTIL</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>			
		</ATTRINFO>		
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="#">
				<OIDNAME>1.3.6.1.2.1.25.1.6.0</OIDNAME>
			</OID>
			<ATTRNAME>PROCESSES</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>			
		</ATTRINFO>		
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="pages">
				<OIDNAME>1.3.6.1.2.1.25.2.3.1.6</OIDNAME>
				<OIDINDEX type="storedValue" >
					<OIDINDEXNAME>Real Memory</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MEM_USED</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>PERCENT</ATTRCOMPUTATION>
			<ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="pages">
					<OIDNAME>1.3.6.1.2.1.25.2.3.1.5</OIDNAME>
					<OIDINDEX type="storedValue" >
						<OIDINDEXNAME>Real Memory</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="pages">
				<OIDNAME>1.3.6.1.2.1.25.2.3.1.6</OIDNAME>
				<OIDINDEX type="storedValue" >
					<OIDINDEXNAME>Swap Space</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>SWAP_USED</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>PERCENT</ATTRCOMPUTATION>
			<ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="pages">
					<OIDNAME>1.3.6.1.2.1.25.2.3.1.5</OIDNAME>
					<OIDINDEX type="storedValue" >
						<OIDINDEXNAME>Swap Space</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
		</ATTRINFO>		
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="pages">
				<OIDNAME>1.3.6.1.2.1.25.2.3.1.5</OIDNAME>
				<OIDINDEX type="storedValue" >
					<OIDINDEXNAME>Swap Space</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>SWAP_TOTAL</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION>TOMB</ATTRCOMPUTATION>			
			<ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="#">
					<OIDNAME>1.3.6.1.2.1.25.2.3.1.4</OIDNAME>
					<OIDINDEX type="storedValue" >
						<OIDINDEXNAME>Swap Space</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="pages">
				<OIDNAME>1.3.6.1.2.1.25.2.3.1.5</OIDNAME>
				<OIDINDEX type="storedValue" >
					<OIDINDEXNAME>Real Memory</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MEM_TOTAL</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION>TOMB</ATTRCOMPUTATION>			
			<ATTRDEPENDSON>
				<OID representedby="value" type="scalar" returns="#">
					<OIDNAME>1.3.6.1.2.1.25.2.3.1.4</OIDNAME>
					<OIDINDEX type="storedValue" >
						<OIDINDEXNAME>Real Memory</OIDINDEXNAME>
						<OIDINDEXNUM>1</OIDINDEXNUM>
					</OIDINDEX>
				</OID>
			</ATTRDEPENDSON>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="timeticks">
				<OIDNAME>1.3.6.1.2.1.25.1.1.0</OIDNAME>
			</OID>
			<ATTRNAME>UPTIME</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>			
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>						
		</ATTRINFO>		
	</ATTRSET>
</SNMPDATA>
