<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SNMPDATA [
        <!ELEMENT SNMPDATA (ATTRSET+)>
        <!ELEMENT ATTRSET (ATTRINFO+)>
        <!ATTLIST ATTRSET
        platform (all | windows | unix | nt | win2k | linux | solaris | hpux | aix | nt4) #REQUIRED
>
        <!ELEMENT ATTRINFO (OID, ATTRNAME, ATTRTYPE, ATTRCOMPUTATION, ATTRDEPENDSON?)>
        <!ELEMENT OID (OIDNAME, OIDINDEX*)>
        <!ATTLIST OID
        representedby (value | string) #REQUIRED
                type (scalar | columnar) #REQUIRED
                returns (number | string | kb | bytes | mb | pages) #REQUIRED
>
        <!ELEMENT ATTRNAME (#PCDATA)>
        <!ELEMENT ATTRTYPE (#PCDATA)>
        <!ELEMENT ATTRCOMPUTATION (#PCDATA)>
        <!ELEMENT ATTRDEPENDSON (OID+)>
        <!ELEMENT OIDNAME (#PCDATA)>
        <!ELEMENT OIDINDEX (OIDINDEXNAME, OIDINDEXNUM)>
        <!ATTLIST OIDINDEX type (string | number) #REQUIRED >
        <!ATTLIST OIDINDEX inputType (asis | fromInput) "fromInput">
        <!ELEMENT OIDINDEXNAME (#PCDATA)>
        <!ELEMENT OIDINDEXNUM (#PCDATA)>
]>
<SNMPDATA>
	<ATTRSET platform="unix">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="#">
				<OIDNAME>1.3.6.1.2.1.68.1.3.1.4</OIDNAME>
				<OIDINDEX type="storedInput" >
					<OIDINDEXNAME>VRRP_ID</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>AVAILABILITY</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>RESOLVE</ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="#">
				<OIDNAME>1.3.6.1.2.1.68.2.4.1.1</OIDNAME>
				<OIDINDEX type="storedInput" >
					<OIDINDEXNAME>VRRP_ID</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MASTER_TIMES</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>
		</ATTRINFO>		
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="#">
				<OIDNAME>1.3.6.1.2.1.68.1.3.1.3</OIDNAME>
				<OIDINDEX type="storedInput" >
					<OIDINDEXNAME>VRRP_ID</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>OPER_STATE</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION>RESOLVE</ATTRCOMPUTATION>			
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="#">
				<OIDNAME>1.3.6.1.2.1.68.1.3.1.5</OIDNAME>
				<OIDINDEX type="storedInput" >
					<OIDINDEXNAME>VRRP_ID</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PRIORITY</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>			
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="#">
				<OIDNAME>1.3.6.1.2.1.68.1.3.1.6</OIDNAME>
				<OIDINDEX type="storedInput" >
					<OIDINDEXNAME>VRRP_ID</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>NO_ASSOC_IP</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>			
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="#">
				<OIDNAME>1.3.6.1.2.1.68.1.3.1.7</OIDNAME>
				<OIDINDEX type="storedInput" >
					<OIDINDEXNAME>VRRP_ID</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>MASTER_IP</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>			
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="timeticks">
				<OIDNAME>1.3.6.1.2.1.68.1.3.1.13</OIDNAME>
				<OIDINDEX type="storedInput" >
					<OIDINDEXNAME>VRRP_ID</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>UPTIME</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>			
			<ATTRCOMPUTATION>ASIS</ATTRCOMPUTATION>						
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="#">
				<OIDNAME>1.3.6.1.2.1.68.1.3.1.14</OIDNAME>
				<OIDINDEX type="storedInput" >
					<OIDINDEXNAME>VRRP_ID</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>PROTOCOL</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION>RESOLVE</ATTRCOMPUTATION>			
		</ATTRINFO>
	</ATTRSET>
</SNMPDATA>
