=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/ntsysmon/conf/MetaFile.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT MetaData (ManagedObject, Attributes)>

<!ELEMENT ManagedObject (ChildBasicInfo, ChildAppsInfo?,ParentBasicInfo?,ParentAppsInfo?)>
<!ELEMENT ChildBasicInfo EMPTY>
<!ATTLIST ChildBasicInfo
	MoTypeId CDATA #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ParentMoType CDATA #IMPLIED
	MoTypeType (SNMP | APPS | PERS) #REQUIRED
	EndUserCreatable (Y | N) "Y"
	GUIDisplayable	(Y | N)	"Y"
	EndUserDeletable (Y | N) "Y"
	IsAutoCreated (Y | N) "N"
	OneInstancePerParent (Y | N) "N"
	EndUserReportable (Y | N) "Y"
	HasCustomizedGUI (Y | N) "N"
>

<!ELEMENT ParentBasicInfo EMPTY>
<!ATTLIST ParentBasicInfo
	MoTypeId CDATA #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ParentMoType CDATA #IMPLIED
	MoTypeType (SNMP | APPS | PERS) #REQUIRED
	EndUserCreatable (Y | N) "Y"
	GUIDisplayable	(Y | N)	"Y"
	EndUserDeletable (Y | N) "Y"
	IsAutoCreated (Y | N) "N"
	OneInstancePerParent (Y | N) "N"
	EndUserReportable (Y | N) "Y"
	HasCustomizedGUI (Y | N) "N"
>
<!ELEMENT ChildAppsInfo EMPTY>
<!ATTLIST ChildAppsInfo
	OS CDATA "Any"
    OSName CDATA "Any"
	Version CDATA "1.0"
	ClassName CDATA #REQUIRED
	GUIMonitorGroup CDATA "OTHER" 
	VendorName CDATA "ProactiveNet Inc." 
	BuildDescription CDATA "This_Is_A_Sample_Build_Description" 
	MinVersion CDATA "4.1.2" 
	MinBuild CDATA "32" 
	IsSchedulable (Y | N)  "Y"
	MustRunOnAgent (Y | N)  "N"
	IsStatic (Y | N)  "N"
	IsNewFrameWork (Y | N)  "N"
	HasMoreInfo (Y | N)  "Y"
	SupportFlashCheck (Y | N)  "Y"
>
<!ELEMENT ParentAppsInfo EMPTY>
<!ATTLIST ParentAppsInfo
	OS CDATA "Any"
	OSName CDATA "Any"
	Version CDATA "1.0"
	ClassName CDATA #REQUIRED
	GUIMonitorGroup CDATA "OTHER" 
	VendorName CDATA "ProactiveNet Inc." 
	BuildDescription CDATA "This_Is_A_Sample_Build_Description" 
	MinVersion CDATA "4.1.2" 
	MinBuild CDATA "32" 
	IsSchedulable (Y | N)  "Y"
	MustRunOnAgent (Y | N)  "N"
	IsStatic (Y | N)  "N"
	IsNewFrameWork (Y | N)  "N"
	HasMoreInfo (Y | N)  "Y"
	SupportFlashCheck (Y | N)  "Y"
>
<!ELEMENT Attributes (Persistent+ | Snmp | Application)>

<!ELEMENT Persistent EMPTY>
<!ATTLIST Persistent
	AttrId CDATA #REQUIRED
	DisplayType (Boolean | Integer | Float | String | IPAddress | DateTime | MOReference | EmailAddress | Attribute | MOType | Group | MOReferenceAny | UnsignedInteger | MoReferenceAny) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	UpperLimit CDATA "0"
	LowerLimit CDATA "0"
	DefaultValue CDATA ""
	EndUserReportable (Y | N) "N"
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsForcedDBKey (Y | N) "N"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	HasLowerLimit (Y | N) "N"
	HasUpperLimit (Y | N) "N"
	IsArrayOfObjects (Y | N) "N"
	IsDefaultValueSet (Y | N) "N"
>

<!ELEMENT Snmp (SnmpInput*, SnmpConfig*, SnmpStats*)>
<!ELEMENT SnmpInput EMPTY>
<!ATTLIST SnmpInput
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	DisplayType (Boolean | Integer | Float | String | IPAddress | MOReference | Password) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	IsDefaultValueSet (Y | N) "N"
>
<!ELEMENT SnmpConfig EMPTY>
<!ATTLIST SnmpConfig
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	DisplayType (Boolean | Integer | String | IPAddress | DateTime | MOReference | Password) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ColumnName CDATA #REQUIRED
	TableName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	EndUserReportable (Y | N) "Y"
	UseAsSecondDBKey (Y | N) "N"
	GUIRequiredOnCreate (Y | N) "N"
	GUIEditable (Y | N) "N"
	IsAutoCreated (Y | N) "N"
	IsGeneratedDBKey (Y | N) "N"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "N"
	UseAsPrimaryDBKey (Y | N) "N"
	IsDefaultValueSet (Y | N) "N"
>
<!ELEMENT SnmpStats (CoreSnmpStats, PinPoint?, Threshold*, SigThreshold*)>
<!ELEMENT CoreSnmpStats EMPTY>
<!ATTLIST CoreSnmpStats
	AttrId CDATA #REQUIRED
	DisplayType (Integer | Float) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ColumnName CDATA #REQUIRED
	TableName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	EndUserReportable (Y | N) "N"
	IsAutoCreated (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "N"
	GUIGraphedByDefault (Y | N) "N"
>
<!ELEMENT PinPoint EMPTY>
<!ATTLIST PinPoint
	PinpointType (Availability | ResponseTime | System | OTHER) "OTHER"
	PinpointAbsoluteRank (0 | 1 | 2 | 3 | 4 | 5) "3"
	PinpointAboveBaselineRank (0 | 1 | 2 | 3 | 4 | 5) "3"
	PinpointBelowBaselineRank (0 | 1 | 2 | 3 | 4 | 5) "3"
>
<!ELEMENT Threshold EMPTY>
<!ATTLIST Threshold
	ThresholdSeverity (NORMAL | MAJOR | MINOR | CRITICAL | UNSET) #REQUIRED
	ThresholdValue CDATA #REQUIRED
	ThresholdType CDATA #REQUIRED
	ThresholdDuration CDATA #REQUIRED
>

<!ELEMENT SigThreshold EMPTY>
<!ATTLIST SigThreshold
	SigThresholdSeverity (NORMAL | MAJOR | MINOR | CRITICAL | UNSET) #REQUIRED
	SigThresholdDuration CDATA #REQUIRED
	SigThresholdType CDATA #REQUIRED
    baselineThreshold CDATA #REQUIRED
    SigThresholdAbsPadFactor CDATA #REQUIRED
    SigThresholdPctPadFactor CDATA #REQUIRED
    SigThresholdSuppressFlag ( Y | N ) "N"
>

<!ELEMENT Application (ParentAppsInput*,AppsInput*,AppsConfig*, AppsStats*, Bundle?)>
<!ELEMENT ParentAppsInput EMPTY>
<!ATTLIST ParentAppsInput
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	UsrAttrId CDATA #IMPLIED 
	DisplayType (Boolean | Integer | Float | String | IPAddress | MOReference | Password | Group | FilePathName) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	IsDefaultValueSet (Y | N) "N"
	UseAsInstanceName (Y | N) "N"
	GUIHasListOfChoice (Y | N) "N"
>
<!ELEMENT AppsInput EMPTY>
<!ATTLIST AppsInput
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	UsrAttrId CDATA #IMPLIED 
	DisplayType (Boolean | Integer | Float | String | IPAddress | MOReference | Password | Group | FilePathName) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	IsDefaultValueSet (Y | N) "N"
	UseAsInstanceName (Y | N) "N"
	GUIHasListOfChoice (Y | N) "N"
>

<!ELEMENT AppsConfig EMPTY>
<!ATTLIST AppsConfig
	AttrId CDATA #REQUIRED
	UsrAttrId CDATA #REQUIRED
	DisplayType (Boolean | Integer | Float | String | MOReference) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	GUIStringLength CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	IsAutoCreated (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	UseAsInstanceName (Y | N) "N"
>
<!ELEMENT AppsStats (CoreAppsStats, PinPoint?, Threshold*, SigThreshold*)>
<!ELEMENT CoreAppsStats EMPTY>
<!ATTLIST CoreAppsStats
	AttrId CDATA #REQUIRED
	UsrAttrId CDATA #IMPLIED
	DisplayType (Integer | Float) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ColumnName CDATA #REQUIRED
	TableName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	GUIStringLength CDATA "0"
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	GUIDisplayable (Y | N) "Y"
	UseNormalDistribution (Y | N) "Y"
	GUIGraphedByDefault (Y | N) "Y"
>
<!ELEMENT Bundle (File*, Permissions*)>
<!ELEMENT File EMPTY>
<!ATTLIST File
	Name CDATA #REQUIRED
>
<!ELEMENT Permissions EMPTY>
<!ATTLIST Permissions
	Filename CDATA #REQUIRED
	Value CDATA #REQUIRED
>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/WMIVam/conf/WMIVamMeta.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MetaData SYSTEM "../../../sysdata/dtd/MetaFile.dtd">
<MetaData>
  <ManagedObject>
<ParentBasicInfo MoTypeId="500012" MoTypeType="APPS" ParentMoType="1" EndUserReportable="N" UniqueName="1WMIVam" GUIDisplayName="WMIVam Info" OneInstancePerParent="Y" EndUserCreatable="Y" GUIDisplayable="Y" EndUserDeletable="Y" IsAutoCreated="N" HasCustomizedGUI="N"/>
<ParentAppsInfo ClassName="com.proactivenet.monitors.WMIVam.WMIVam" HasMoreInfo="N" OS="Windows" IsStatic="Y" IsNewFrameWork="Y" IsSchedulable="N" Version="1.0" OSName="Any" GUIMonitorGroup="OTHER" VendorName="ProactiveNet Inc." BuildDescription="This_Is_A_Sample_Build_Description" MinVersion="4.1.2" MinBuild="32" MustRunOnAgent="N" SupportFlashCheck="Y" HasArrayAttribute="N" IsGroupResourcePool="N" IsIndexMon="N" AutoDiscoveryEnabled="N"/>
<BasicInfo HasCustomizedGUI="Y" MoTypeId="500013" MoTypeType="APPS" ParentMoType="500012" UniqueName="WMIVam" GUIDisplayName="Windows Management Instrumentation" EndUserCreatable="Y" GUIDisplayable="Y" EndUserDeletable="Y" IsAutoCreated="N" OneInstancePerParent="N" EndUserReportable="Y"/>
<AppsInfo ClassName="com.proactivenet.monitors.WMIVam.WMIVam" HasMoreInfo="N" OS="Windows" Version="1.0" OSName="Any" GUIMonitorGroup="OTHER" VendorName="ProactiveNet Inc." BuildDescription="This_Is_A_Sample_Build_Description" MinVersion="4.1.2" MinBuild="32" IsSchedulable="Y" MustRunOnAgent="N" IsStatic="N" IsNewFrameWork="N" SupportFlashCheck="Y" HasArrayAttribute="N" IsGroupResourcePool="N" IsIndexMon="N" AutoDiscoveryEnabled="N"/>
</ManagedObject>

  <Attributes>
<Application>
<ParentAppsInput AttrId="500012999" UsrAttrId="999" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="String" UseAsMODisplayName="Y" DefaultValue="WMIVam" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" GUIDisplaySequenceNumber="0" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" GUIDisplayable="Y" GUIInputOnCreate="Y" UseAsInstanceName="N" IsInputAttribute="Y" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
<AppsInput AttrId="500013003" UsrAttrId="3" UniqueName="OBJECT" GUIDisplayName="Class" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="51" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="String" GUIHasListOfChoice="Y" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIDisplayable="Y" GUIInputOnCreate="Y" IsInputAttribute="Y" DefaultValue="" UseNormalDistribution="N"/>
<AppsInput AttrId="500013004" UsrAttrId="4" UniqueName="INSTANCE" GUIDisplayName="Instance" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="52" UseAsInstanceName="Y" IsDefaultValueSet="Y" GUIRequiredOnCreate="N" DisplayType="String" GUIHasListOfChoice="Y" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIDisplayable="Y" GUIInputOnCreate="Y" IsInputAttribute="Y" DefaultValue="" UseNormalDistribution="N"/>
<AppsInput AttrId="500013005" UsrAttrId="5" UniqueName="PROPERTY" GUIDisplayName="Properties" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="53" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="String" GUIHasListOfChoice="Y" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIDisplayable="Y" GUIInputOnCreate="Y" IsInputAttribute="Y" DefaultValue="" UseNormalDistribution="N"/>
<AppsInput AttrId="500013006" UsrAttrId="6" UniqueName="TEST" GUIDisplayName="Test" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="52" UseAsInstanceName="Y" IsDefaultValueSet="Y" GUIRequiredOnCreate="N" DisplayType="String" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIDisplayable="Y" GUIInputOnCreate="Y" IsInputAttribute="Y" GUIHasListOfChoice="N" DefaultValue="" UseNormalDistribution="N"/>
</Application>
</Attributes>
</MetaData>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/ntdiskmon/conf/NTDiskMonMeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MetaData SYSTEM "../../../pronto/sysdata/dtd/MetaFile.dtd">
<!-- NTDiskIntelliMeta.xml -->

<MetaData>
  <ManagedObject>
    <ParentBasicInfo MoTypeId="21012" MoTypeType="APPS" ParentMoType="1" EndUserReportable="N" UniqueName="NTDiskInfo" GUIDisplayName="NT Disk Space Monitor" OneInstancePerParent="Y"/>
    <ParentAppsInfo ClassName="ntdiskmon" Version="2.0" OS="Windows" IsStatic="Y" IsSchedulable="N"/>
    <BasicInfo MoTypeId="21015" MoTypeType="APPS" ParentMoType="21012" UniqueName="NTDiskIntelli" GUIDisplayName="Windows Disk Performance"/>
    <AppsInfo ClassName="ntdiskmon" OS="Windows" Version="2.0"/>
<!--
<BasicInfo
      MoTypeId="35101"
      MoTypeType="APPS"
      ParentMoType="1"
      UniqueName="NTDiskMonGenMon"
      GUIDisplayName="Windows Disk Performance"
    />
    <AppsInfo
      ClassName="GenMonBase"
      Version="2.0"
      OS="Windows"
    />
    -->
  </ManagedObject>
  <Attributes>
    <Application>
      <!--
<ParentAppsInput
        AttrId="210151"
        UsrAttrId="22"
        UniqueName="INSTANCE_NAME"
        GUIDisplayName="Instance Name"
        GUIInputType="CFG"
        ScaleFactor="1000"
        IsDefaultValueSet="Y"
        DisplayType="String"
        UseAsMODisplayName="Y"
        DefaultValue="NT Disk Monitor"
		IsInputAttribute="Y" 
		AttrReferenceType="Unknown"       
		 />
-->	
	  <AppsInput AttrId="21015986" UsrAttrId="6" UniqueName="INPUTFILE" GUIDisplayName="Input XML file name " GUIEditable="N" GUIInputType="CFG" ScaleFactor="1" GUIDisplayable="N" IsDefaultValueSet="Y" GUIInputOnCreate="N" AttrReferenceType="Unknown" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue="ntdiskmon\\NTDiskMonGenMon.xml"/>
      <AppsInput AttrId="210151" UsrAttrId="22" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="1" IsDefaultValueSet="Y" GUIRequiredOnCreate="N" DisplayType="String" UseAsMODisplayName="Y"/>
      <AppsInput AttrId="210152" UsrAttrId="23" UniqueName="DISK" GUIDisplayName="Physical Disk" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="51" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="String" GUIHasListOfChoice="Y" DefaultValue="0"/>
      <AppsInput AttrId="210161" UsrAttrId="-6" UniqueName="COLLECTDATA" GUIDisplayName="Collect Data" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Boolean" DefaultValue="1"/>
      <AppsInput AttrId="210156" UsrAttrId="-3" UniqueName="SRCIP" GUIDisplayName="Source Agent" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="2" MoReferenceType="10000" GUIRequiredOnCreate="N" DisplayType="MOReference"/>
      <AppsInput AttrId="210165" UsrAttrId="993" UniqueName="TARGETIP" GUIDisplayName="Target IP/Host Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="3" IsDefaultValueSet="Y" DisplayType="IPAddress" DefaultValue="0"/>
      <AppsInput AttrId="210158" UsrAttrId="-5" UniqueName="STSPOLLTIMEOUT" GUIDisplayName="Statistics Poll Timeout" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="30"/>
      <AppsInput AttrId="210157" UsrAttrId="-4" UniqueName="STSPOLLPERIOD" GUIDisplayName="Statistics Poll Interval" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="300"/>
<AppsInput AttrId="21015980" UsrAttrId="980" UniqueName="CI_TOKEN_ID" GUIDisplayName="CI Token ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="52" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue="" />
<AppsInput AttrId="21015981" UsrAttrId="981" UniqueName="CI_ID" GUIDisplayName="CI ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="53" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue="" />
<AppsInput AttrId="21015982" UsrAttrId="982" UniqueName="CI_ALIAS" GUIDisplayName="CI Alias" GUIInputType="CFG" GUIEditable="Y" GUIStringLength="255" ScaleFactor="1000" GUIDisplaySequenceNumber="54" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue="" />
      <AppsInput AttrId="21015468" UsrAttrId="468" UniqueName="TENANT_ID" GUIDisplayName="Tenant ID" MoReferenceType="0" AttrReferenceType="Unknown" DefaultValue="" ScaleFactor="0" GUIStringLength="255" GUIDisplaySequenceNumber="55" GUIDisplayable="N" DisplayType="String" UseAsMODisplayName="N" GUIInputType="CFG" IsInputAttribute="Y" IsAutoCreated="Y" GUIRequiredOnCreate="N" GUIEditable="N" GUIInputOnCreate="Y" IsDefaultValueSet="N" UseAsInstanceName="N" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
      <AppsConfig AttrId="210164" UsrAttrId="27" UniqueName="PW_MON_VER" GUIDisplayName="Monitor Version" DisplayType="String" ScaleFactor="1000" DefaultValue="1.0"/>
      <AppsStats>
        <CoreAppsStats AttrId="210171" UsrAttrId="33" UniqueName="DISK_WRITE_QUEUE_LEN" GUIDisplayName="Avg. Disk Write Queue Len" TableName="NTDISKPERF" ColumnName="WRITEQUEUE" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="#" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="210169" UsrAttrId="31" UniqueName="DISK_WRITES_SEC" GUIDisplayName="Disk Writes/Sec" TableName="NTDISKPERF" ColumnName="WRITESEC" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="#" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="210154" UsrAttrId="25" UniqueName="DISK_TIME" GUIDisplayName="% Disk Time" TableName="NTDISKPERF" ColumnName="DISKTIMEPCT" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="%"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="210166" UsrAttrId="28" UniqueName="DISK_READ_TIME" GUIDisplayName="% Disk Read Time" TableName="NTDISKPERF" ColumnName="READTIME" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="%" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="210155" UsrAttrId="26" UniqueName="DISK_TRANSFER" GUIDisplayName="Avg. Disk Transfer Time" TableName="NTDISKPERF" ColumnName="AVGDISKTRAN" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="ms" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="210170" UsrAttrId="32" UniqueName="DISK_READ_QUEUE_LEN" GUIDisplayName="Avg. Disk Read Queue Len" TableName="NTDISKPERF" ColumnName="READQUEUE" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="#" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="210168" UsrAttrId="30" UniqueName="DISK_READS_SEC" GUIDisplayName="Disk Reads/Sec" TableName="NTDISKPERF" ColumnName="READSEC" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="#" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="210153" UsrAttrId="24" UniqueName="DISK_QUEUE_LEN" GUIDisplayName="Avg. Disk Queue Length" TableName="NTDISKPERF" ColumnName="AVGQLEN" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="#"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="210167" UsrAttrId="29" UniqueName="DISK_WRITE_TIME" GUIDisplayName="% Disk Write Time" TableName="NTDISKPERF" ColumnName="WRITETIME" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="%" GUIGraphedByDefault="N"/>
      </AppsStats>
    </Application>
  </Attributes>
</MetaData>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/MySQLQuery/conf/MySQLQueryMeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MetaData SYSTEM "../../../pronto/sysdata/dtd/MetaFile.dtd">
<!-- MySQLQueryQueryMeta.xml -->


<MetaData>
  <ManagedObject>
    <ParentBasicInfo MoTypeId="43752" MoTypeType="APPS" ParentMoType="1" EndUserReportable="N" UniqueName="MySQL" GUIDisplayName="My SQL" OneInstancePerParent="Y" EndUserCreatable="Y" GUIDisplayable="Y" EndUserDeletable="Y" IsAutoCreated="N" HasCustomizedGUI="N"/>
    <ParentAppsInfo ClassName="com.proactivenet.monitors.MySQLQuery.MySQLQuery" Version="1.0" OS="Any" IsStatic="Y" IsSchedulable="N" OSName="Any" IsNewFrameWork="Y" SupportFlashCheck="Y"/>
    <BasicInfo MoTypeId="43753" MoTypeType="APPS" ParentMoType="43752" UniqueName="MySQLQuery" GUIDisplayName="MySQL Query" EndUserCreatable="Y" GUIDisplayable="Y" EndUserDeletable="Y" IsAutoCreated="N" OneInstancePerParent="N" EndUserReportable="Y" HasCustomizedGUI="N"/>
    <AppsInfo ClassName="com.proactivenet.monitors.MySQLQuery.MySQLQuery" Version="1.0" OS="Any" OSName="Any" IsSchedulable="Y" MustRunOnAgent="N" IsStatic="N" HasMoreInfo="Y" SupportFlashCheck="Y"/>
  </ManagedObject>
  <Attributes>
    <Application>
      <ParentAppsInput AttrId="43752999" UsrAttrId="999" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="String" UseAsMODisplayName="Y" DefaultValue="MySQL"/>
      <AppsInput AttrId="43753999" UsrAttrId="999" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="1" IsDefaultValueSet="Y" GUIRequiredOnCreate="N" DisplayType="String" UseAsMODisplayName="Y"/>
      <AppsInput AttrId="43753994" UsrAttrId="994" UniqueName="SRCIP" GUIDisplayName="Source Agent" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="2" MoReferenceType="10000" GUIRequiredOnCreate="N" DisplayType="MOReference"/>
      <AppsInput AttrId="43753020" UsrAttrId="020" UniqueName="TARGETIP" GUIDisplayName="Target IP/Host Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="51" GUIDisplayable="N" IsDefaultValueSet="Y" DisplayType="IPAddress" DefaultValue="0" IsAutoCreated="Y" GUIRequiredOnCreate="N" GUIEditable="N" UseAsMODisplayName="N" GUIInputOnCreate="N" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
      <AppsInput AttrId="43753989" UsrAttrId="989" GUIDisplayName="Target Device" UniqueName="DNSIP" GUIDisplaySequenceNumber="3" GUIDisplayable="Y" DisplayType="String" GUIInputType="CFG" IsInputAttribute="Y" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" GUIInputOnCreate="Y" IsDefaultValueSet="Y" DefaultValue="0.0.0.0" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
      <AppsInput AttrId="43753004" UsrAttrId="004" UniqueName="PORT" GUIDisplayName="Port" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="4" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="3306"/>
      <AppsInput AttrId="43753005" UsrAttrId="005" UniqueName="DB" GUIDisplayName="Database Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="5" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="String"/>
      <AppsInput AttrId="43753006" UsrAttrId="006" UniqueName="USER_NAME" GUIDisplayName="User Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="Y" GUIDisplaySequenceNumber="6" IsDefaultValueSet="Y" DisplayType="String"/>
      <AppsInput AttrId="43753007" UsrAttrId="007" UniqueName="PASSWORD" GUIDisplayName="Password" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" GUIDisplaySequenceNumber="7" GUIRequiredOnCreate="N" IsDefaultValueSet="Y" DisplayType="Password"/>
      <AppsInput AttrId="43753008" UsrAttrId="008" UniqueName="SQL" GUIDisplayName="SQL Statement" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="8" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="String" DefaultValue="select count(*) from mysql.user;"/>
      <AppsInput AttrId="43753995" UsrAttrId="995" UniqueName="COLLECTDATA" GUIDisplayName="Collect Data" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Boolean" DefaultValue="1"/>
      <AppsInput AttrId="43753991" UsrAttrId="991" UniqueName="RETRY_COUNT" GUIDisplayName="Retry Count" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="3"/>
      <AppsInput AttrId="43753992" UsrAttrId="992" UniqueName="RETRY_DELAY" GUIDisplayName="Retry Delay" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="20"/>
      <AppsInput AttrId="43753998" UsrAttrId="998" UniqueName="STSPOLLPERIOD" GUIDisplayName="Statistics Poll Interval" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="300"/>
      <AppsInput AttrId="43753997" UsrAttrId="997" UniqueName="STSPOLLTIMEOUT" GUIDisplayName="Statistics Poll Timeout" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="30"/>
      <AppsInput AttrId="43753980" UsrAttrId="980" UniqueName="CI_TOKEN_ID" GUIDisplayName="CI Token ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="52" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="43753981" UsrAttrId="981" UniqueName="CI_ID" GUIDisplayName="CI ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="53" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="43753982" UsrAttrId="982" UniqueName="CI_ALIAS" GUIDisplayName="CI Alias" GUIInputType="CFG" GUIEditable="Y" GUIStringLength="255" ScaleFactor="1000" GUIDisplaySequenceNumber="54" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="43753468" UsrAttrId="468" UniqueName="TENANT_ID" GUIDisplayName="Tenant ID" MoReferenceType="0" AttrReferenceType="Unknown" DefaultValue="" ScaleFactor="0" GUIStringLength="255" GUIDisplaySequenceNumber="55" GUIDisplayable="N" DisplayType="String" UseAsMODisplayName="N" GUIInputType="CFG" IsInputAttribute="Y" IsAutoCreated="Y" GUIRequiredOnCreate="N" GUIEditable="N" GUIInputOnCreate="Y" IsDefaultValueSet="N" UseAsInstanceName="N" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
      <AppsConfig AttrId="43753993" UsrAttrId="993" UniqueName="PW_MON_VER" GUIDisplayName="Monitor Version" DisplayType="String" ScaleFactor="1000" IsDefaultValueSet="Y" DefaultValue="1.0"/>
      <AppsStats>
        <CoreAppsStats AttrId="43753101" UsrAttrId="101" UniqueName="AVAILABILITY" GUIDisplayName="Availability" TableName="MYSQLQUERY" ColumnName="AVAILABILITY" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="%" GUIGraphedByDefault="Y" MoReferenceType="0" GUIDisplayable="Y" UseNormalDistribution="Y"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="43753102" UsrAttrId="102" UniqueName="CONNECTTIME" GUIDisplayName="Connect Time" TableName="MYSQLQUERY" ColumnName="CONNTIME" ScaleFactor="1000" UseNormalDistribution="N" DisplayType="Integer" UnitOfMeasurement="ms" MoReferenceType="0" GUIDisplayable="Y" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="43753103" UsrAttrId="103" UniqueName="RESPONSETIME" GUIDisplayName="Response Time" TableName="MYSQLQUERY" ColumnName="RESPTIME" ScaleFactor="1000" UseNormalDistribution="N" DisplayType="Integer" UnitOfMeasurement="ms" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="43753104" UsrAttrId="104" UniqueName="VALUE" GUIDisplayName="Value" TableName="MYSQLQUERY" ColumnName="QUERYVAL" ScaleFactor="1000" UseNormalDistribution="N" DisplayType="Integer" UnitOfMeasurement="#" GUIGraphedByDefault="N"/>
      </AppsStats>
    </Application>
  </Attributes>
</MetaData>
