=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/ntsysmon/conf/MetaFile.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT MetaData (ManagedObject, Attributes)>

<!ELEMENT ManagedObject (ChildBasicInfo, ChildAppsInfo?,ParentBasicInfo?,ParentAppsInfo?)>
<!ELEMENT ChildBasicInfo EMPTY>
<!ATTLIST ChildBasicInfo
	MoTypeId CDATA #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ParentMoType CDATA #IMPLIED
	MoTypeType (SNMP | APPS | PERS) #REQUIRED
	EndUserCreatable (Y | N) "Y"
	GUIDisplayable	(Y | N)	"Y"
	EndUserDeletable (Y | N) "Y"
	IsAutoCreated (Y | N) "N"
	OneInstancePerParent (Y | N) "N"
	EndUserReportable (Y | N) "Y"
	HasCustomizedGUI (Y | N) "N"
>

<!ELEMENT ParentBasicInfo EMPTY>
<!ATTLIST ParentBasicInfo
	MoTypeId CDATA #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ParentMoType CDATA #IMPLIED
	MoTypeType (SNMP | APPS | PERS) #REQUIRED
	EndUserCreatable (Y | N) "Y"
	GUIDisplayable	(Y | N)	"Y"
	EndUserDeletable (Y | N) "Y"
	IsAutoCreated (Y | N) "N"
	OneInstancePerParent (Y | N) "N"
	EndUserReportable (Y | N) "Y"
	HasCustomizedGUI (Y | N) "N"
>
<!ELEMENT ChildAppsInfo EMPTY>
<!ATTLIST ChildAppsInfo
	OS CDATA "Any"
    OSName CDATA "Any"
	Version CDATA "1.0"
	ClassName CDATA #REQUIRED
	GUIMonitorGroup CDATA "OTHER" 
	VendorName CDATA "ProactiveNet Inc." 
	BuildDescription CDATA "This_Is_A_Sample_Build_Description" 
	MinVersion CDATA "4.1.2" 
	MinBuild CDATA "32" 
	IsSchedulable (Y | N)  "Y"
	MustRunOnAgent (Y | N)  "N"
	IsStatic (Y | N)  "N"
	IsNewFrameWork (Y | N)  "N"
	HasMoreInfo (Y | N)  "Y"
	SupportFlashCheck (Y | N)  "Y"
>
<!ELEMENT ParentAppsInfo EMPTY>
<!ATTLIST ParentAppsInfo
	OS CDATA "Any"
	OSName CDATA "Any"
	Version CDATA "1.0"
	ClassName CDATA #REQUIRED
	GUIMonitorGroup CDATA "OTHER" 
	VendorName CDATA "ProactiveNet Inc." 
	BuildDescription CDATA "This_Is_A_Sample_Build_Description" 
	MinVersion CDATA "4.1.2" 
	MinBuild CDATA "32" 
	IsSchedulable (Y | N)  "Y"
	MustRunOnAgent (Y | N)  "N"
	IsStatic (Y | N)  "N"
	IsNewFrameWork (Y | N)  "N"
	HasMoreInfo (Y | N)  "Y"
	SupportFlashCheck (Y | N)  "Y"
>
<!ELEMENT Attributes (Persistent+ | Snmp | Application)>

<!ELEMENT Persistent EMPTY>
<!ATTLIST Persistent
	AttrId CDATA #REQUIRED
	DisplayType (Boolean | Integer | Float | String | IPAddress | DateTime | MOReference | EmailAddress | Attribute | MOType | Group | MOReferenceAny | UnsignedInteger | MoReferenceAny) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	UpperLimit CDATA "0"
	LowerLimit CDATA "0"
	DefaultValue CDATA ""
	EndUserReportable (Y | N) "N"
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsForcedDBKey (Y | N) "N"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	HasLowerLimit (Y | N) "N"
	HasUpperLimit (Y | N) "N"
	IsArrayOfObjects (Y | N) "N"
	IsDefaultValueSet (Y | N) "N"
>

<!ELEMENT Snmp (SnmpInput*, SnmpConfig*, SnmpStats*)>
<!ELEMENT SnmpInput EMPTY>
<!ATTLIST SnmpInput
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	DisplayType (Boolean | Integer | Float | String | IPAddress | MOReference | Password) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	IsDefaultValueSet (Y | N) "N"
>
<!ELEMENT SnmpConfig EMPTY>
<!ATTLIST SnmpConfig
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	DisplayType (Boolean | Integer | String | IPAddress | DateTime | MOReference | Password) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ColumnName CDATA #REQUIRED
	TableName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	EndUserReportable (Y | N) "Y"
	UseAsSecondDBKey (Y | N) "N"
	GUIRequiredOnCreate (Y | N) "N"
	GUIEditable (Y | N) "N"
	IsAutoCreated (Y | N) "N"
	IsGeneratedDBKey (Y | N) "N"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "N"
	UseAsPrimaryDBKey (Y | N) "N"
	IsDefaultValueSet (Y | N) "N"
>
<!ELEMENT SnmpStats (CoreSnmpStats, PinPoint?, Threshold*, SigThreshold*)>
<!ELEMENT CoreSnmpStats EMPTY>
<!ATTLIST CoreSnmpStats
	AttrId CDATA #REQUIRED
	DisplayType (Integer | Float) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ColumnName CDATA #REQUIRED
	TableName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	EndUserReportable (Y | N) "N"
	IsAutoCreated (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "N"
	GUIGraphedByDefault (Y | N) "N"
>
<!ELEMENT PinPoint EMPTY>
<!ATTLIST PinPoint
	PinpointType (Availability | ResponseTime | System | OTHER) "OTHER"
	PinpointAbsoluteRank (0 | 1 | 2 | 3 | 4 | 5) "3"
	PinpointAboveBaselineRank (0 | 1 | 2 | 3 | 4 | 5) "3"
	PinpointBelowBaselineRank (0 | 1 | 2 | 3 | 4 | 5) "3"
>
<!ELEMENT Threshold EMPTY>
<!ATTLIST Threshold
	ThresholdSeverity (NORMAL | MAJOR | MINOR | CRITICAL | UNSET) #REQUIRED
	ThresholdValue CDATA #REQUIRED
	ThresholdType CDATA #REQUIRED
	ThresholdDuration CDATA #REQUIRED
>

<!ELEMENT SigThreshold EMPTY>
<!ATTLIST SigThreshold
	SigThresholdSeverity (NORMAL | MAJOR | MINOR | CRITICAL | UNSET) #REQUIRED
	SigThresholdDuration CDATA #REQUIRED
	SigThresholdType CDATA #REQUIRED
    baselineThreshold CDATA #REQUIRED
    SigThresholdAbsPadFactor CDATA #REQUIRED
    SigThresholdPctPadFactor CDATA #REQUIRED
    SigThresholdSuppressFlag ( Y | N ) "N"
>

<!ELEMENT Application (ParentAppsInput*,AppsInput*,AppsConfig*, AppsStats*, Bundle?)>
<!ELEMENT ParentAppsInput EMPTY>
<!ATTLIST ParentAppsInput
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	UsrAttrId CDATA #IMPLIED 
	DisplayType (Boolean | Integer | Float | String | IPAddress | MOReference | Password | Group | FilePathName) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	IsDefaultValueSet (Y | N) "N"
	UseAsInstanceName (Y | N) "N"
	GUIHasListOfChoice (Y | N) "N"
>
<!ELEMENT AppsInput EMPTY>
<!ATTLIST AppsInput
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	UsrAttrId CDATA #IMPLIED 
	DisplayType (Boolean | Integer | Float | String | IPAddress | MOReference | Password | Group | FilePathName) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	IsDefaultValueSet (Y | N) "N"
	UseAsInstanceName (Y | N) "N"
	GUIHasListOfChoice (Y | N) "N"
>

<!ELEMENT AppsConfig EMPTY>
<!ATTLIST AppsConfig
	AttrId CDATA #REQUIRED
	UsrAttrId CDATA #REQUIRED
	DisplayType (Boolean | Integer | Float | String | MOReference) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	GUIStringLength CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	IsAutoCreated (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	UseAsInstanceName (Y | N) "N"
>
<!ELEMENT AppsStats (CoreAppsStats, PinPoint?, Threshold*, SigThreshold*)>
<!ELEMENT CoreAppsStats EMPTY>
<!ATTLIST CoreAppsStats
	AttrId CDATA #REQUIRED
	UsrAttrId CDATA #IMPLIED
	DisplayType (Integer | Float) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ColumnName CDATA #REQUIRED
	TableName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	GUIStringLength CDATA "0"
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	GUIDisplayable (Y | N) "Y"
	UseNormalDistribution (Y | N) "Y"
	GUIGraphedByDefault (Y | N) "Y"
>
<!ELEMENT Bundle (File*, Permissions*)>
<!ELEMENT File EMPTY>
<!ATTLIST File
	Name CDATA #REQUIRED
>
<!ELEMENT Permissions EMPTY>
<!ATTLIST Permissions
	Filename CDATA #REQUIRED
	Value CDATA #REQUIRED
>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/PatrolVSMCNTRMon/conf/PatrolVSMCNTRMonMeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MetaData SYSTEM "../../../pronto/sysdata/dtd/MetaFile.dtd">
<!-- Level 4 -->

<MetaData>
  <ManagedObject>
    <ParentBasicInfo MoTypeId="48060" MoTypeType="APPS" ParentMoType="1" EndUserReportable="N" UniqueName="PATROL_VSM_CNTR" GUIDisplayName="Patrol VSM Container" OneInstancePerParent="Y"/>
    <ParentAppsInfo ClassName="com.proactivenet.monitors.PatrolVSAdapter.PatrolVSPollManager" IsAdapterFrameWork="Y" IsStatic="Y" SupportFlashCheck="N" IsNewFrameWork="Y" IsSchedulable="N"/>
    <BasicInfo MoTypeId="48061" MoTypeType="APPS" ParentMoType="48060" UniqueName="VSM_CNTR" GUIDisplayName="VSM"/>
    <AppsInfo ClassName="com.proactivenet.monitors.PatrolVSAdapter.PatrolVSPollManager" IsAutoSyncEnabled="Y" IsAdapterFrameWork="Y" IsStatic="Y" SupportFlashCheck="N" AdapterType="60008" IsNewFrameWork="Y"/>
  </ManagedObject>
  <Attributes>
    <Application>
      <ParentAppsInput AttrId="48060999" UsrAttrId="999" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsInputAttribute="Y" DisplayType="String" UseAsMODisplayName="Y" DefaultValue="VSM_CNTR"/>
      <AppsInput AttrId="48061011" UsrAttrId="11" UniqueName="APP_INSTANCE_NAME" GUIDisplayName="App Instance Name" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsAutoDiscoverable="Y" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String"/>
      <AppsInput AttrId="48061999" UsrAttrId="999" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="1" IsDefaultValueSet="Y" GUIInputOnCreate="N" AttrReferenceType="Unknown" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" UseAsMODisplayName="Y" DefaultValue=""/>
      <AppsInput AttrId="48061008" UsrAttrId="8" UniqueName="USERNAME" GUIDisplayName="User Name" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="5" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsInputAttribute="Y" DisplayType="String" DefaultValue="admin"/>
      <AppsInput AttrId="48061994" UsrAttrId="994" UniqueName="COLLECTDATA" GUIDisplayName="Collect Data" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsInputAttribute="Y" DisplayType="Boolean" DefaultValue="1"/>
      <AppsInput AttrId="48061014" UsrAttrId="14" UniqueName="PARENT_PATH" GUIDisplayName="Parent Path" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsAutoDiscoverable="Y" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue="/VSM/VSM_VC/VSM_HOST"/>
      <AppsInput AttrId="48061050" UsrAttrId="50" UniqueName="PARENT_ADAPTER" GUIDisplayName="Adapter" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="2" IsDefaultValueSet="Y" GUIInputOnCreate="N" AttrReferenceType="Unknown" MoReferenceType="60008" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="MOReference" DefaultValue="-1"/>
      <AppsInput AttrId="48061998" UsrAttrId="998" UniqueName="STSPOLLPERIOD" GUIDisplayName="Statistics Poll Interval" GUIInputType="CTL" ScaleFactor="1" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsInputAttribute="Y" DisplayType="Integer" DefaultValue="900"/>
      <AppsInput AttrId="48061001" UsrAttrId="1" UniqueName="PARENT_ID" GUIDisplayName="Parent ID" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" IsDefaultValueSet="Y" AttrReferenceType="Unknown" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="Integer" DefaultValue="48077"/>
      <AppsInput AttrId="48061003" UsrAttrId="3" UniqueName="APP_PATH" GUIDisplayName="Application Path" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsAutoDiscoverable="Y" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String"/>
      <AppsInput AttrId="48061004" UsrAttrId="4" UniqueName="DNSIP" GUIDisplayName="PATROL Proxy Agent Hostname/IP" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="3" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsInputAttribute="Y" DisplayType="String"/>
      <AppsInput AttrId="48061007" UsrAttrId="7" UniqueName="SRCIP" GUIDisplayName="Source Agent" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" GUIDisplaySequenceNumber="2" IsDefaultValueSet="Y" MoReferenceType="10000" IsInputAttribute="Y" DisplayType="MOReference" DefaultValue="-1"/>
      <AppsInput AttrId="48061006" UsrAttrId="6" UniqueName="PASSWORD" GUIDisplayName="Password" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" GUIDisplaySequenceNumber="6" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsInputAttribute="Y" DisplayType="Password" DefaultValue="admin"/>
      <AppsInput AttrId="48061009" UsrAttrId="9" UniqueName="PATROL_AGENT_NAME" GUIDisplayName="Patrol Agent" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsAutoDiscoverable="Y" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String"/>
      <AppsInput AttrId="48061010" UsrAttrId="10" UniqueName="APP_DEF_NAME" GUIDisplayName="Application Class Definition Name" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsAutoDiscoverable="Y" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue="VSM_CNTR"/>
      <AppsInput AttrId="48061005" UsrAttrId="5" UniqueName="PORT" GUIDisplayName="PATROL Proxy Agent Port" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="4" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsInputAttribute="Y" DisplayType="Integer" DefaultValue="3182"/>
      <AppsInput AttrId="48061997" UsrAttrId="997" UniqueName="STSPOLLTIMEOUT" GUIDisplayName="Statistics Poll Timeout" GUIInputType="CTL" ScaleFactor="1" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsInputAttribute="Y" DisplayType="Integer" DefaultValue="120"/>
      <AppsInput AttrId="48061013" UsrAttrId="13" UniqueName="INST_PATH" GUIDisplayName="Instance Path" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" IsDefaultValueSet="Y" AttrReferenceType="Unknown" IsAutoDiscoverable="Y" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String"/>
      <AppsInput AttrId="48061980" UsrAttrId="980" UniqueName="CI_TOKEN_ID" GUIDisplayName="CI Token ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="1" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="48061981" UsrAttrId="981" UniqueName="CI_ID" GUIDisplayName="CI ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="2" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="48061982" UsrAttrId="982" UniqueName="CI_ALIAS" GUIDisplayName="CI Alias" GUIInputType="CFG" GUIEditable="Y" GUIStringLength="255" ScaleFactor="1000" GUIDisplaySequenceNumber="3" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="48061468" UsrAttrId="468" UniqueName="TENANT_ID" GUIDisplayName="Tenant ID" MoReferenceType="0" AttrReferenceType="Unknown" DefaultValue="" ScaleFactor="0" GUIStringLength="255" GUIDisplaySequenceNumber="7" GUIDisplayable="N" DisplayType="String" UseAsMODisplayName="N" GUIInputType="CFG" IsInputAttribute="Y" IsAutoCreated="Y" GUIRequiredOnCreate="N" GUIEditable="N" GUIInputOnCreate="Y" IsDefaultValueSet="N" UseAsInstanceName="N" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
      <AppsStats>
        <CoreAppsStats AttrId="48061200" UsrAttrId="200" UniqueName="PN_DUMMY_STATS" GUIDisplayName="PN Dummy Stats" TableName="VSM_CNTR" ColumnName="PN_DUMMY_STATS" ScaleFactor="1" GUIDisplayable="N" AttrReferenceType="Unknown" DisplayType="Integer" UnitOfMeasurement="#" GUIGraphedByDefault="N"/>
      </AppsStats>
    </Application>
  </Attributes>
</MetaData>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/vamdatastoremon/conf/vamdatastoremonMeta.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MetaData SYSTEM "../../../sysdata/dtd/MetaFile.dtd">
<MetaData>
  <ManagedObject>
<ParentBasicInfo MoTypeId="500006" MoTypeType="APPS" ParentMoType="1" EndUserReportable="N" UniqueName="1vamdatastoremon" GUIDisplayName="vamdatastoremon Info" OneInstancePerParent="Y" EndUserCreatable="Y" GUIDisplayable="Y" EndUserDeletable="Y" IsAutoCreated="N" HasCustomizedGUI="N"/>
<ParentAppsInfo ClassName="com.proactivenet.monitors.vamdatastoremon.vamdatastoremon" HasMoreInfo="N" OS="SunOS:Windows" IsStatic="Y" IsNewFrameWork="Y" IsSchedulable="N" Version="1.0" OSName="Any" GUIMonitorGroup="OTHER" VendorName="ProactiveNet Inc." BuildDescription="This_Is_A_Sample_Build_Description" MinVersion="4.1.2" MinBuild="32" MustRunOnAgent="N" SupportFlashCheck="Y" HasArrayAttribute="N" IsGroupResourcePool="N" IsIndexMon="N" AutoDiscoveryEnabled="N"/>
<BasicInfo HasCustomizedGUI="Y" MoTypeId="500007" MoTypeType="APPS" ParentMoType="500006" UniqueName="vamdatastoremon" GUIDisplayName="VAM Adaptor for Data Store" EndUserCreatable="Y" GUIDisplayable="Y" EndUserDeletable="Y" IsAutoCreated="N" OneInstancePerParent="N" EndUserReportable="Y"/>
<AppsInfo ClassName="com.proactivenet.monitors.vamdatastoremon.vamdatastoremon" HasMoreInfo="N" OS="SunOS:Windows" Version="1.0" OSName="Any" GUIMonitorGroup="OTHER" VendorName="ProactiveNet Inc." BuildDescription="This_Is_A_Sample_Build_Description" MinVersion="4.1.2" MinBuild="32" IsSchedulable="Y" MustRunOnAgent="N" IsStatic="N" IsNewFrameWork="N" SupportFlashCheck="Y" HasArrayAttribute="N" IsGroupResourcePool="N" IsIndexMon="N" AutoDiscoveryEnabled="N"/>
</ManagedObject>

  <Attributes>
<Application>
<ParentAppsInput AttrId="500006999" UsrAttrId="999" UniqueName="Instance Name" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="String" UseAsMODisplayName="Y" DefaultValue="Adaptor for Data Store" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" GUIDisplaySequenceNumber="0" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" GUIDisplayable="Y" GUIInputOnCreate="Y" UseAsInstanceName="N" IsInputAttribute="Y" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
<AppsInput AttrId="500007004" UsrAttrId="4" UniqueName="TABLE_NAME" GUIDisplayName="Table Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="51" UseAsInstanceName="Y" IsDefaultValueSet="Y" GUIRequiredOnCreate="N" DisplayType="String" GUIHasListOfChoice="Y" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIDisplayable="Y" GUIInputOnCreate="Y" IsInputAttribute="Y" DefaultValue="" UseNormalDistribution="N"/>
<AppsInput AttrId="500007005" UsrAttrId="5" UniqueName="COLUMN_NAME" GUIDisplayName="Column Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="52" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="String" GUIHasListOfChoice="Y" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIDisplayable="Y" GUIInputOnCreate="Y" IsInputAttribute="Y" DefaultValue="" UseNormalDistribution="N"/>
<AppsInput AttrId="500007006" UsrAttrId="6" UniqueName="VALIDATE" GUIDisplayName="VALIDATE" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" GUIDisplaySequenceNumber="53" IsDefaultValueSet="Y" DisplayType="String" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIInputOnCreate="Y" UseAsInstanceName="N" IsInputAttribute="Y" GUIHasListOfChoice="N" DefaultValue="" UseNormalDistribution="N"/>
<AppsInput AttrId="500007015" UsrAttrId="15" UniqueName="VALIDATE_COLUMN" GUIDisplayName="Table Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="51" UseAsInstanceName="Y" IsDefaultValueSet="Y" GUIRequiredOnCreate="N" DisplayType="String" GUIHasListOfChoice="Y" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIDisplayable="Y" GUIInputOnCreate="Y" IsInputAttribute="Y" DefaultValue="" UseNormalDistribution="N"/>
<AppsInput AttrId="705102716" UsrAttrId="12" UniqueName="WHERE_CLAUSE" GUIDisplayName="Where clause" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="53" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="String" GUIHasListOfChoice="Y" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIDisplayable="Y" GUIInputOnCreate="Y" IsInputAttribute="Y" DefaultValue="" UseNormalDistribution="N"/>
<AppsInput AttrId="500007016" UsrAttrId="16" UniqueName="COLNAMES" GUIDisplayName="Column Names" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" GUIDisplaySequenceNumber="55" IsDefaultValueSet="Y" DisplayType="String" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIInputOnCreate="Y" UseAsInstanceName="N" IsInputAttribute="Y" GUIHasListOfChoice="N" DefaultValue="" UseNormalDistribution="N"/>
</Application>
</Attributes>
</MetaData>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/ntdiskmon/conf/NTDiskSpaceMeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MetaData SYSTEM "../../../pronto/sysdata/dtd/MetaFile.dtd">
<!-- NTDiskSpaceMeta.xml -->

<MetaData>
  <ManagedObject>
    <ParentBasicInfo MoTypeId="21012" MoTypeType="APPS" ParentMoType="1" EndUserReportable="N" UniqueName="NTDiskInfo" GUIDisplayName="NT Disk Space Monitor" OneInstancePerParent="Y"/>
    <ParentAppsInfo ClassName="ntdiskmon" Version="2.0" OS="Windows" IsStatic="Y" IsSchedulable="N"/>
    <BasicInfo MoTypeId="21013" MoTypeType="APPS" ParentMoType="21012" UniqueName="NTDiskSpace" GUIDisplayName="Windows File System"/>
    <AppsInfo ClassName="ntdiskmon" Version="2.0" OS="Windows"/>
  </ManagedObject>
  <Attributes>
    <Application>
      <ParentAppsInput AttrId="210130" UsrAttrId="1" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="String" UseAsMODisplayName="Y" DefaultValue="Disk Space Monitor"/>
      <AppsInput AttrId="210143" UsrAttrId="-6" UniqueName="COLLECTDATA" GUIDisplayName="Collect Data" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Boolean" DefaultValue="1"/>
      <AppsInput AttrId="210138" UsrAttrId="-3" UniqueName="SRCIP" GUIDisplayName="Source Agent" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="2" MoReferenceType="10000" GUIRequiredOnCreate="N" DisplayType="MOReference"/>
      <AppsInput AttrId="210142" UsrAttrId="-2" UniqueName="CFGPOLLTIMEOUT" GUIDisplayName="Configuration Poll Timeout" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="20"/>
      <AppsInput AttrId="210132" UsrAttrId="3" UniqueName="SCRIPTFILE" GUIDisplayName="Script File to Run" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" IsDefaultValueSet="Y" GUIInputOnCreate="N" GUIRequiredOnCreate="N" DisplayType="String" DefaultValue="ntdskmon.exe"/>
      <AppsInput AttrId="210141" UsrAttrId="-1" UniqueName="CFGPOLLPERIOD" GUIDisplayName="Configuration Poll Interval" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="86400"/>
      <AppsInput AttrId="210131" UsrAttrId="2" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="1" IsDefaultValueSet="Y" GUIRequiredOnCreate="N" DisplayType="String" UseAsMODisplayName="Y"/>
      <AppsInput AttrId="210140" UsrAttrId="-5" UniqueName="STSPOLLTIMEOUT" GUIDisplayName="Statistics Poll Timeout" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="20"/>
      <AppsInput AttrId="210139" UsrAttrId="-4" UniqueName="STSPOLLPERIOD" GUIDisplayName="Statistics Poll Interval" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="300"/>
      <AppsInput AttrId="210147" UsrAttrId="993" UniqueName="TARGETIP" GUIDisplayName="Target IP/Host Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="3" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="IPAddress" DefaultValue="0"/>
      <AppsInput AttrId="210133" UsrAttrId="4" UniqueName="NO_OF_INPUT_PARAMS" GUIDisplayName="No Of Input Params" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" IsDefaultValueSet="Y" GUIInputOnCreate="N" GUIRequiredOnCreate="N" DisplayType="Integer" DefaultValue="1"/>
      <AppsInput AttrId="210134" UsrAttrId="5" UniqueName="DIR" GUIDisplayName="Drive" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="51" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="String" GUIHasListOfChoice="Y"/>
      <AppsInput AttrId="21013980" UsrAttrId="980" UniqueName="CI_TOKEN_ID" GUIDisplayName="CI Token ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="52" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="21013981" UsrAttrId="981" UniqueName="CI_ID" GUIDisplayName="CI ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="53" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="21013982" UsrAttrId="982" UniqueName="CI_ALIAS" GUIDisplayName="CI Alias" GUIInputType="CFG" GUIEditable="Y" GUIStringLength="255" ScaleFactor="1000" GUIDisplaySequenceNumber="54" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="21013468" UsrAttrId="468" UniqueName="TENANT_ID" GUIDisplayName="Tenant ID" MoReferenceType="0" AttrReferenceType="Unknown" DefaultValue="" ScaleFactor="0" GUIStringLength="255" GUIDisplaySequenceNumber="55" GUIDisplayable="N" DisplayType="String" UseAsMODisplayName="N" GUIInputType="CFG" IsInputAttribute="Y" IsAutoCreated="Y" GUIRequiredOnCreate="N" GUIEditable="N" GUIInputOnCreate="Y" IsDefaultValueSet="N" UseAsInstanceName="N" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
      <AppsConfig AttrId="210146" UsrAttrId="9" UniqueName="PW_MON_VER" GUIDisplayName="Monitor Version" DisplayType="String" ScaleFactor="1000"/>
      <AppsConfig AttrId="210135" UsrAttrId="6" UniqueName="TOTAL_SIZE" GUIDisplayName="Size" DisplayType="String" ScaleFactor="1000"/>
      <AppsStats>
        <CoreAppsStats AttrId="210137" UsrAttrId="8" UniqueName="AVAILABILITY" GUIDisplayName="Availability" TableName="NTFILESYSTEM" ColumnName="AVAILABILITY" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="%" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="210136" UsrAttrId="7" UniqueName="USED_PERCENT" GUIDisplayName="Used" TableName="NTFILESYSTEM" ColumnName="USEDPCT" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="%"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="2101335" UsrAttrId="35" UniqueName="FREE_DISK_SPACE" GUIDisplayName="Free Disk Space" TableName="NTFILESYSTEM" ColumnName="FREEDSKSPC" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="MB" GUIGraphedByDefault="N"/>
      </AppsStats>
    </Application>
  </Attributes>
</MetaData>
