=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/ntsysmon/conf/MetaFile.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT MetaData (ManagedObject, Attributes)>

<!ELEMENT ManagedObject (ChildBasicInfo, ChildAppsInfo?,ParentBasicInfo?,ParentAppsInfo?)>
<!ELEMENT ChildBasicInfo EMPTY>
<!ATTLIST ChildBasicInfo
	MoTypeId CDATA #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ParentMoType CDATA #IMPLIED
	MoTypeType (SNMP | APPS | PERS) #REQUIRED
	EndUserCreatable (Y | N) "Y"
	GUIDisplayable	(Y | N)	"Y"
	EndUserDeletable (Y | N) "Y"
	IsAutoCreated (Y | N) "N"
	OneInstancePerParent (Y | N) "N"
	EndUserReportable (Y | N) "Y"
	HasCustomizedGUI (Y | N) "N"
>

<!ELEMENT ParentBasicInfo EMPTY>
<!ATTLIST ParentBasicInfo
	MoTypeId CDATA #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ParentMoType CDATA #IMPLIED
	MoTypeType (SNMP | APPS | PERS) #REQUIRED
	EndUserCreatable (Y | N) "Y"
	GUIDisplayable	(Y | N)	"Y"
	EndUserDeletable (Y | N) "Y"
	IsAutoCreated (Y | N) "N"
	OneInstancePerParent (Y | N) "N"
	EndUserReportable (Y | N) "Y"
	HasCustomizedGUI (Y | N) "N"
>
<!ELEMENT ChildAppsInfo EMPTY>
<!ATTLIST ChildAppsInfo
	OS CDATA "Any"
    OSName CDATA "Any"
	Version CDATA "1.0"
	ClassName CDATA #REQUIRED
	GUIMonitorGroup CDATA "OTHER" 
	VendorName CDATA "ProactiveNet Inc." 
	BuildDescription CDATA "This_Is_A_Sample_Build_Description" 
	MinVersion CDATA "4.1.2" 
	MinBuild CDATA "32" 
	IsSchedulable (Y | N)  "Y"
	MustRunOnAgent (Y | N)  "N"
	IsStatic (Y | N)  "N"
	IsNewFrameWork (Y | N)  "N"
	HasMoreInfo (Y | N)  "Y"
	SupportFlashCheck (Y | N)  "Y"
>
<!ELEMENT ParentAppsInfo EMPTY>
<!ATTLIST ParentAppsInfo
	OS CDATA "Any"
	OSName CDATA "Any"
	Version CDATA "1.0"
	ClassName CDATA #REQUIRED
	GUIMonitorGroup CDATA "OTHER" 
	VendorName CDATA "ProactiveNet Inc." 
	BuildDescription CDATA "This_Is_A_Sample_Build_Description" 
	MinVersion CDATA "4.1.2" 
	MinBuild CDATA "32" 
	IsSchedulable (Y | N)  "Y"
	MustRunOnAgent (Y | N)  "N"
	IsStatic (Y | N)  "N"
	IsNewFrameWork (Y | N)  "N"
	HasMoreInfo (Y | N)  "Y"
	SupportFlashCheck (Y | N)  "Y"
>
<!ELEMENT Attributes (Persistent+ | Snmp | Application)>

<!ELEMENT Persistent EMPTY>
<!ATTLIST Persistent
	AttrId CDATA #REQUIRED
	DisplayType (Boolean | Integer | Float | String | IPAddress | DateTime | MOReference | EmailAddress | Attribute | MOType | Group | MOReferenceAny | UnsignedInteger | MoReferenceAny) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	UpperLimit CDATA "0"
	LowerLimit CDATA "0"
	DefaultValue CDATA ""
	EndUserReportable (Y | N) "N"
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsForcedDBKey (Y | N) "N"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	HasLowerLimit (Y | N) "N"
	HasUpperLimit (Y | N) "N"
	IsArrayOfObjects (Y | N) "N"
	IsDefaultValueSet (Y | N) "N"
>

<!ELEMENT Snmp (SnmpInput*, SnmpConfig*, SnmpStats*)>
<!ELEMENT SnmpInput EMPTY>
<!ATTLIST SnmpInput
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	DisplayType (Boolean | Integer | Float | String | IPAddress | MOReference | Password) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	IsDefaultValueSet (Y | N) "N"
>
<!ELEMENT SnmpConfig EMPTY>
<!ATTLIST SnmpConfig
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	DisplayType (Boolean | Integer | String | IPAddress | DateTime | MOReference | Password) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ColumnName CDATA #REQUIRED
	TableName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	EndUserReportable (Y | N) "Y"
	UseAsSecondDBKey (Y | N) "N"
	GUIRequiredOnCreate (Y | N) "N"
	GUIEditable (Y | N) "N"
	IsAutoCreated (Y | N) "N"
	IsGeneratedDBKey (Y | N) "N"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "N"
	UseAsPrimaryDBKey (Y | N) "N"
	IsDefaultValueSet (Y | N) "N"
>
<!ELEMENT SnmpStats (CoreSnmpStats, PinPoint?, Threshold*, SigThreshold*)>
<!ELEMENT CoreSnmpStats EMPTY>
<!ATTLIST CoreSnmpStats
	AttrId CDATA #REQUIRED
	DisplayType (Integer | Float) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ColumnName CDATA #REQUIRED
	TableName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	EndUserReportable (Y | N) "N"
	IsAutoCreated (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "N"
	GUIGraphedByDefault (Y | N) "N"
>
<!ELEMENT PinPoint EMPTY>
<!ATTLIST PinPoint
	PinpointType (Availability | ResponseTime | System | OTHER) "OTHER"
	PinpointAbsoluteRank (0 | 1 | 2 | 3 | 4 | 5) "3"
	PinpointAboveBaselineRank (0 | 1 | 2 | 3 | 4 | 5) "3"
	PinpointBelowBaselineRank (0 | 1 | 2 | 3 | 4 | 5) "3"
>
<!ELEMENT Threshold EMPTY>
<!ATTLIST Threshold
	ThresholdSeverity (NORMAL | MAJOR | MINOR | CRITICAL | UNSET) #REQUIRED
	ThresholdValue CDATA #REQUIRED
	ThresholdType CDATA #REQUIRED
	ThresholdDuration CDATA #REQUIRED
>

<!ELEMENT SigThreshold EMPTY>
<!ATTLIST SigThreshold
	SigThresholdSeverity (NORMAL | MAJOR | MINOR | CRITICAL | UNSET) #REQUIRED
	SigThresholdDuration CDATA #REQUIRED
	SigThresholdType CDATA #REQUIRED
    baselineThreshold CDATA #REQUIRED
    SigThresholdAbsPadFactor CDATA #REQUIRED
    SigThresholdPctPadFactor CDATA #REQUIRED
    SigThresholdSuppressFlag ( Y | N ) "N"
>

<!ELEMENT Application (ParentAppsInput*,AppsInput*,AppsConfig*, AppsStats*, Bundle?)>
<!ELEMENT ParentAppsInput EMPTY>
<!ATTLIST ParentAppsInput
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	UsrAttrId CDATA #IMPLIED 
	DisplayType (Boolean | Integer | Float | String | IPAddress | MOReference | Password | Group | FilePathName) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	IsDefaultValueSet (Y | N) "N"
	UseAsInstanceName (Y | N) "N"
	GUIHasListOfChoice (Y | N) "N"
>
<!ELEMENT AppsInput EMPTY>
<!ATTLIST AppsInput
	AttrId CDATA #REQUIRED
	GUIInputType (CFG | CTL) #REQUIRED
	UsrAttrId CDATA #IMPLIED 
	DisplayType (Boolean | Integer | Float | String | IPAddress | MOReference | Password | Group | FilePathName) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	GUIStringLength CDATA "0"
	MoReferenceType CDATA "0"
	AttrReferenceType (ANY | CFG | CTL | STS) "ANY"	
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	DefaultValue CDATA ""
	GUIRequiredOnCreate (Y | N) "Y"
	GUIEditable (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	GUIInputOnCreate (Y | N) "Y"
	IsDefaultValueSet (Y | N) "N"
	UseAsInstanceName (Y | N) "N"
	GUIHasListOfChoice (Y | N) "N"
>

<!ELEMENT AppsConfig EMPTY>
<!ATTLIST AppsConfig
	AttrId CDATA #REQUIRED
	UsrAttrId CDATA #REQUIRED
	DisplayType (Boolean | Integer | Float | String | MOReference) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	GUIStringLength CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	IsAutoCreated (Y | N) "Y"
	UseAsMODisplayName (Y | N) "N"
	GUIDisplayable (Y | N) "Y"
	UseAsInstanceName (Y | N) "N"
>
<!ELEMENT AppsStats (CoreAppsStats, PinPoint?, Threshold*, SigThreshold*)>
<!ELEMENT CoreAppsStats EMPTY>
<!ATTLIST CoreAppsStats
	AttrId CDATA #REQUIRED
	UsrAttrId CDATA #IMPLIED
	DisplayType (Integer | Float) #REQUIRED
	GUIDisplayName CDATA #REQUIRED
	UniqueName CDATA #REQUIRED
	ColumnName CDATA #REQUIRED
	TableName CDATA #REQUIRED
	UnitOfMeasurement CDATA ""
	GUIStringLength CDATA "0"
	ScaleFactor CDATA "0"
	GUIDisplaySequenceNumber CDATA "0"
	GUIDisplayable (Y | N) "Y"
	UseNormalDistribution (Y | N) "Y"
	GUIGraphedByDefault (Y | N) "Y"
>
<!ELEMENT Bundle (File*, Permissions*)>
<!ELEMENT File EMPTY>
<!ATTLIST File
	Name CDATA #REQUIRED
>
<!ELEMENT Permissions EMPTY>
<!ATTLIST Permissions
	Filename CDATA #REQUIRED
	Value CDATA #REQUIRED
>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/GenMonConf/conf/GenMonBaseMeta.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE MetaData SYSTEM "../../../pronto/sysdata/dtd/MetaFile.dtd">
<!-- GenMonBaseMeta.xml -->

<MetaData>
  <ManagedObject>


<ParentBasicInfo
      MoTypeId="500026"
      MoTypeType="APPS"
      ParentMoType="1"
      EndUserReportable="N"
      UniqueName="1GenMonBase"
      GUIDisplayName="Generic Monitor Base Info"
      OneInstancePerParent="Y"
    />
<ParentAppsInfo
      ClassName="com.proactivenet.monitors.GenMonBase.Wizard"
      HasMoreInfo="N"
      OS="Any"
      IsStatic="Y"
      IsNewFrameWork="Y"
      IsSchedulable="N"
    />

<BasicInfo
      HasCustomizedGUI="Y"
      MoTypeId="500027"
      MoTypeType="APPS"
      ParentMoType="500026"
      UniqueName="GenMonBase"
      GUIDisplayName="Generic Monitor Base"
    />
    <AppsInfo
      ClassName="com.proactivenet.monitors.GenMonBase.Wizard"
      HasMoreInfo="N"
      OS="Any"
    />
  </ManagedObject>

  <Attributes>
    <Application>


<ParentAppsInput
        AttrId="500026999"
        UsrAttrId="999"
        UniqueName="Instance Name"
        GUIDisplayName="Instance Name"
        GUIInputType="CFG"
        ScaleFactor="1000"
        IsDefaultValueSet="Y"
        DisplayType="String"
        UseAsMODisplayName="Y"
        DefaultValue="Generic Monitor"
      />

<AppsInput
        AttrId="500027004"
        UsrAttrId="4"
        UniqueName="WMI"
        GUIDisplayName="WMI Attribute Choice"
        GUIInputType="CFG"
        ScaleFactor="1000"
        GUIDisplaySequenceNumber="52"
        UseAsInstanceName="Y"
        IsDefaultValueSet="Y"
        GUIRequiredOnCreate="N"
        DisplayType="String"
        GUIHasListOfChoice="Y"
      />
      <AppsInput
        AttrId="500027005"
        UsrAttrId="5"
        UniqueName="PDH"
        GUIDisplayName="PDH Attribute Choice"
        GUIInputType="CFG"
        ScaleFactor="1000"
        GUIDisplaySequenceNumber="53"
        UseAsInstanceName="Y"
        IsDefaultValueSet="Y"
        DisplayType="String"
        GUIHasListOfChoice="Y"
      />
      <AppsInput
        AttrId="500027006"
        UsrAttrId="6"
        UniqueName="Perf Info"
        GUIDisplayName="Perf Info Attribute Choice"
        GUIInputType="CFG"
        ScaleFactor="1000"
        GUIDisplayable="N"
        GUIDisplaySequenceNumber="54"
        IsDefaultValueSet="Y"
        DisplayType="String"
      />
      <AppsInput
        AttrId="500027003"
        UsrAttrId="3"
        UniqueName="Event Log"
        GUIDisplayName="Event Log Attribute Choice"
        GUIInputType="CFG"
        ScaleFactor="1000"
        GUIDisplaySequenceNumber="51"
        UseAsInstanceName="Y"
        IsDefaultValueSet="Y"
        DisplayType="String"
        GUIHasListOfChoice="Y"
      />
      <AppsInput
        AttrId="500027007"
        UsrAttrId="7"
        UniqueName="Test"
        GUIDisplayName="Test Button"
        GUIInputType="CFG"
        ScaleFactor="1000"
        GUIDisplaySequenceNumber="51"
        UseAsInstanceName="Y"
        IsDefaultValueSet="Y"
        DisplayType="String"
        GUIHasListOfChoice="Y"
      />
      <AppsInput
        AttrId="500027008"
        UsrAttrId="8"
        UniqueName="Comp"
        GUIDisplayName="Composite attribute choice"
        GUIInputType="CFG"
        ScaleFactor="1000"
        GUIDisplaySequenceNumber="51"
        UseAsInstanceName="Y"
        IsDefaultValueSet="Y"
        DisplayType="String"
        GUIHasListOfChoice="Y"
      />
      <AppsInput
        AttrId="500027009"
        UsrAttrId="9"
        UniqueName="File"
        GUIDisplayName="Generic Log File Attribute Choice"
        GUIInputType="CFG"
        ScaleFactor="1000"
        GUIDisplaySequenceNumber="51"
        UseAsInstanceName="Y"
        IsDefaultValueSet="Y"
        DisplayType="String"
        GUIHasListOfChoice="Y"
      />      
    </Application>
  </Attributes>
</MetaData>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/LinuxFileSystemMon/conf/LinuxFileSystemMonMeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MetaData SYSTEM "../../../pronto/sysdata/dtd/MetaFile.dtd">
<!-- LinuxFileSystemMonInMeta.xml -->

<MetaData>
  <ManagedObject>
    <ParentBasicInfo MoTypeId="28150" MoTypeType="APPS" ParentMoType="1" EndUserReportable="N" UniqueName="LinuxFileSystemMon" GUIDisplayName="Linux File System Monitor" OneInstancePerParent="Y"/>
    <ParentAppsInfo ClassName="com.proactivenet.monitors.LinuxFileSystemMon.LinuxFileSystemMon" Version="2.1" OS="Linux" MustRunOnAgent="Y" HasMoreInfo="N" IsStatic="Y" IsSchedulable="N"/>
    <BasicInfo MoTypeId="28151" MoTypeType="APPS" ParentMoType="28150" UniqueName="LinuxFileSystemMonIn" GUIDisplayName="Linux File System"/>
    <AppsInfo ClassName="com.proactivenet.monitors.LinuxFileSystemMon.LinuxFileSystemMon" Version="2.1" OS="Linux" MustRunOnAgent="Y" HasMoreInfo="N"/>
  </ManagedObject>
  <Attributes>
    <Application>
      <ParentAppsInput AttrId="281500" UsrAttrId="1" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="String" UseAsMODisplayName="Y" DefaultValue="Linux File System Monitor"/>
      <AppsInput AttrId="281506" UsrAttrId="7" UniqueName="DIR" GUIDisplayName="Partition / Directory" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="51" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="String" GUIHasListOfChoice="Y"/>
      <AppsInput AttrId="281530" UsrAttrId="30" UniqueName="CHKAVAIL" GUIDisplayName="Check Availability" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="52" UseAsInstanceName="N" IsDefaultValueSet="Y" DisplayType="Boolean" DefaultValue="1" GUIStringLength="0" MoReferenceType="0" AttrReferenceType="ANY" IsAutoCreated="Y" GUIRequiredOnCreate="Y" GUIEditable="Y" UseAsMODisplayName="N" GUIDisplayable="Y" GUIInputOnCreate="Y" IsInputAttribute="Y" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
      <AppsInput AttrId="281501" UsrAttrId="2" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="1" IsDefaultValueSet="Y" GUIRequiredOnCreate="N" DisplayType="String" UseAsMODisplayName="Y"/>
      <AppsInput AttrId="281522" UsrAttrId="-6" UniqueName="COLLECTDATA" GUIDisplayName="Collect Data" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Boolean" DefaultValue="1"/>
      <AppsInput AttrId="281520" UsrAttrId="-1" UniqueName="CFGPOLLPERIOD" GUIDisplayName="Configuration Poll Interval" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="86400"/>
      <AppsInput AttrId="281517" UsrAttrId="-3" UniqueName="SRCIP" GUIDisplayName="Source Agent" GUIEditable="N" GUIInputType="CFG" ScaleFactor="1000" GUIDisplayable="N" GUIDisplaySequenceNumber="2" GUIInputOnCreate="N" MoReferenceType="10000" GUIRequiredOnCreate="N" DisplayType="MOReference"/>
      <AppsInput AttrId="281518" UsrAttrId="-4" UniqueName="STSPOLLPERIOD" GUIDisplayName="Statistics Poll Interval" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="300"/>
      <AppsInput AttrId="28151980" UsrAttrId="980" UniqueName="CI_TOKEN_ID" GUIDisplayName="CI Token ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="53" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="28151981" UsrAttrId="981" UniqueName="CI_ID" GUIDisplayName="CI ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="54" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="28151982" UsrAttrId="982" UniqueName="CI_ALIAS" GUIDisplayName="CI Alias" GUIInputType="CFG" GUIEditable="Y" GUIStringLength="255" ScaleFactor="1000" GUIDisplaySequenceNumber="55" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="28151468" UsrAttrId="468" UniqueName="TENANT_ID" GUIDisplayName="Tenant ID" MoReferenceType="0" AttrReferenceType="Unknown" DefaultValue="" ScaleFactor="0" GUIStringLength="255" GUIDisplaySequenceNumber="56" GUIDisplayable="N" DisplayType="String" UseAsMODisplayName="N" GUIInputType="CFG" IsInputAttribute="Y" IsAutoCreated="Y" GUIRequiredOnCreate="N" GUIEditable="N" GUIInputOnCreate="Y" IsDefaultValueSet="N" UseAsInstanceName="N" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
      <AppsConfig AttrId="281515" UsrAttrId="16" UniqueName="TOTAL_INODES" GUIDisplayName="Total I-Nodes" DisplayType="String" ScaleFactor="1000"/>
      <AppsConfig AttrId="281525" UsrAttrId="25" UniqueName="PW_MON_VER" GUIDisplayName="Monitor Version" DisplayType="String" ScaleFactor="1000"/>
      <AppsConfig AttrId="281528" UsrAttrId="28" UniqueName="DISK_FILESYSTEM" GUIDisplayName="File System" DisplayType="String" ScaleFactor="1000"/>
      <AppsConfig AttrId="281509" UsrAttrId="10" UniqueName="DISK_SIZE" GUIDisplayName="Size" DisplayType="String" ScaleFactor="1000"/>
      <AppsStats>
        <CoreAppsStats AttrId="281511" UsrAttrId="12" UniqueName="DISK_USED_PERCENT" GUIDisplayName="Disk Used" TableName="LNXFILESYS" ColumnName="USEDPCT" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="%"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="281516" UsrAttrId="17" UniqueName="I_NODE_USED_PERCENT" GUIDisplayName="I-Node Used" TableName="LNXFILESYS" ColumnName="INODEUSEDPCT" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="%" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="281512" UsrAttrId="13" UniqueName="AVAILABILITY" GUIDisplayName="Availability" TableName="LNXFILESYS" ColumnName="AVAILABILITY" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="%" GUIGraphedByDefault="N"/>
      </AppsStats>
      <AppsStats>
        <CoreAppsStats AttrId="2815132" UsrAttrId="15" UniqueName="DISK_FREE" GUIDisplayName="Disk Free" TableName="LNXFILESYS" ColumnName="DSKFREE" ScaleFactor="1000" DisplayType="Integer" UnitOfMeasurement="MB" GUIGraphedByDefault="N"/>
      </AppsStats>
    </Application>
  </Attributes>
</MetaData>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/vamscriptmon/conf/VamScriptMonMeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MetaData SYSTEM "../../../pronto/sysdata/dtd/MetaFile.dtd">
<!-- VamScriptMonMeta.xml -->

<MetaData>
  <ManagedObject>


<ParentBasicInfo
      MoTypeId="500010"
      MoTypeType="APPS"
      ParentMoType="1"
      EndUserReportable="N"
      UniqueName="PVamScriptMon"
      GUIDisplayName="VamScriptMon Info"
      OneInstancePerParent="Y"
    />
<ParentAppsInfo
      ClassName="com.proactivenet.monitors.vamscriptmon.vamscriptmon"
      MustRunOnAgent="Y"
      OS="SunOS:Windows"
      IsStatic="Y"
      IsNewFrameWork="Y"
      IsSchedulable="N"
    />

<BasicInfo
      HasCustomizedGUI="Y"
      MoTypeId="500011"
      MoTypeType="APPS"
      ParentMoType="500010"
      UniqueName="VamScriptMon"
      GUIDisplayName="VAM Script Monitor"
    />
    <AppsInfo
      ClassName="com.proactivenet.monitors.vamscriptmon.vamscriptmon"
      HasMoreInfo="N"
      OS="SunOS:Windows"
    />
  </ManagedObject>

  <Attributes>
    <Application>
     <ParentAppsInput
        AttrId="500010999"
        UsrAttrId="999"
        UniqueName="Instance Name"
        GUIDisplayName="Instance Name"
        GUIInputType="CFG"
        ScaleFactor="1000"
        IsDefaultValueSet="Y"
        DisplayType="String"
        UseAsMODisplayName="Y"
        DefaultValue="VAM Script Monitor"
      />
      <AppsInput
        AttrId="500011004"
        UsrAttrId="4"
        UniqueName="TEST"
        GUIDisplayName="Test"
        GUIInputType="CFG"
        ScaleFactor="1000"
        GUIDisplaySequenceNumber="52"
        UseAsInstanceName="Y"
        IsDefaultValueSet="Y"
        GUIRequiredOnCreate="N"
        DisplayType="String"
      />


    </Application>
  </Attributes>
</MetaData>

=== manjunaths069/indegeneous/ngpmon/bin/com/proactivenet/monitors/TivoliEventReceiverMon/conf/TivoliEventRecvMeta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MetaData SYSTEM "../../../pronto/sysdata/dtd/MetaFile.dtd">
<!-- TivoliEventRecvMeta.xml -->

<MetaData>
  <ManagedObject>
    <ParentBasicInfo MoTypeId="31240" MoTypeType="APPS" ParentMoType="1" UniqueName="TivoliERMon" GUIDisplayName="TivoliEventReceiver Monitor" OneInstancePerParent="Y"/>
    <ParentAppsInfo ClassName="com.proactivenet.monitors.TivoliEventReceiverMon.TivoliEventReceiverMon" HasMoreInfo="N" OS="SunOS" IsStatic="Y" SupportFlashCheck="N" IsNewFrameWork="Y" IsSchedulable="N"/>
    <BasicInfo MoTypeId="31241" MoTypeType="APPS" ParentMoType="31240" UniqueName="TivoliEventRecv" GUIDisplayName="Event Receiver for Tivoli"/>
    <AppsInfo ClassName="com.proactivenet.monitors.TivoliEventReceiverMon.TivoliEventReceiverMon" OS="SunOS:Linux:HP-UX:AIX"/>
  </ManagedObject>
  <Attributes>
    <Application>
      <ParentAppsInput AttrId="31240999" UsrAttrId="999" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" UseAsMODisplayName="Y" DisplayType="String" ScaleFactor="1000" DefaultValue="TivoliEventReceiver Monitor"/>
      <AppsInput AttrId="31241999" UsrAttrId="999" UniqueName="INSTANCE_NAME" GUIDisplayName="Instance Name" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="1" IsDefaultValueSet="Y" GUIRequiredOnCreate="N" DisplayType="String" UseAsMODisplayName="Y" DefaultValue="Event Receiver for Tivoli"/>
      <AppsInput AttrId="31241002" UsrAttrId="2" UniqueName="FILTERFILE" GUIDisplayName="Filter File" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="63" IsDefaultValueSet="N" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="31241995" UsrAttrId="995" UniqueName="COLLECTDATA" GUIDisplayName="Collect Data" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Boolean" DefaultValue="1"/>
      <AppsInput AttrId="31241004" UsrAttrId="4" UniqueName="DEVASSOC" GUIDisplayName="Device Associated" GUIInputType="CTL" ScaleFactor="1000" GUIDisplaySequenceNumber="60" GUIRequiredOnCreate="N" DisplayType="Boolean"/>
      <AppsInput AttrId="31241994" UsrAttrId="994" UniqueName="SRCIP" GUIDisplayName="Source Agent" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="2" MoReferenceType="10000" GUIRequiredOnCreate="N" DisplayType="MOReference"/>
      <AppsInput AttrId="31241001" UsrAttrId="1" UniqueName="PORT" GUIDisplayName="Port" GUIInputType="CFG" ScaleFactor="1000" GUIDisplaySequenceNumber="62" UseAsInstanceName="Y" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="5151"/>
      <AppsInput AttrId="31241003" UsrAttrId="3" UniqueName="TARGETIP" GUIDisplayName="Target IP/Host Name" GUIDisplaySequenceNumber="61" GUIInputType="CFG" DisplayType="IPAddress" ScaleFactor="1000"/>
      <AppsInput AttrId="31241998" UsrAttrId="998" UniqueName="STSPOLLPERIOD" GUIDisplayName="Statistics Poll Interval" GUIInputType="CTL" ScaleFactor="1000" IsDefaultValueSet="Y" DisplayType="Integer" DefaultValue="900"/>
      <AppsInput AttrId="31241980" UsrAttrId="980" UniqueName="CI_TOKEN_ID" GUIDisplayName="CI Token ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="64" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="31241981" UsrAttrId="981" UniqueName="CI_ID" GUIDisplayName="CI ID" GUIInputType="CFG" GUIEditable="N" ScaleFactor="1000" GUIDisplaySequenceNumber="65" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="31241982" UsrAttrId="982" UniqueName="CI_ALIAS" GUIDisplayName="CI Alias" GUIInputType="CFG" GUIEditable="Y" GUIStringLength="255" ScaleFactor="1000" GUIDisplaySequenceNumber="66" IsDefaultValueSet="Y" AttrReferenceType="ANY" GUIRequiredOnCreate="N" IsInputAttribute="Y" DisplayType="String" DefaultValue=""/>
      <AppsInput AttrId="31241468" UsrAttrId="468" UniqueName="TENANT_ID" GUIDisplayName="Tenant ID" MoReferenceType="0" AttrReferenceType="Unknown" DefaultValue="" ScaleFactor="0" GUIStringLength="255" GUIDisplaySequenceNumber="67" GUIDisplayable="N" DisplayType="String" UseAsMODisplayName="N" GUIInputType="CFG" IsInputAttribute="Y" IsAutoCreated="Y" GUIRequiredOnCreate="N" GUIEditable="N" GUIInputOnCreate="Y" IsDefaultValueSet="N" UseAsInstanceName="N" GUIHasListOfChoice="N" UseNormalDistribution="N"/>
      <AppsConfig AttrId="31241993" UsrAttrId="993" UniqueName="PW_MON_VER" GUIDisplayName="Monitor Version" DisplayType="String" ScaleFactor="1000"/>
      <AppsStats>
        <CoreAppsStats AttrId="31241100" UsrAttrId="100" UniqueName="NUMEVENTS" GUIDisplayName="Events Received" TableName="TIVOLI_EVENT_REC" ColumnName="EVENT_COUNT" ScaleFactor="1" DisplayType="Integer" UnitOfMeasurement="#"/>
      </AppsStats>
    </Application>
  </Attributes>
</MetaData>
