<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SNMPDATA [
	<!ELEMENT SNMPDATA (ATTRSET+)>
	<!ELEMENT ATTRSET (ATTRINFO+)>
	<!ATTLIST ATTRSET
	platform (all | windows | unix | nt | win2k | linux | solaris | hpux | aix | nt4 | unixA2 ) #REQUIRED
>
	<!ELEMENT ATTRINFO (OID, ATTRNAME, ATTRTYPE, ATTRCOMPUTATION, ATTRDEPENDSON?)>
	<!ELEMENT OID (OIDNAME, OIDINDEX*)>
	<!ATTLIST OID
	representedby (value | string) #REQUIRED
		type (scalar | columnar) #REQUIRED
		returns (number | string | kb | bytes | mb) #REQUIRED
>
	<!ELEMENT ATTRNAME (#PCDATA)>
	<!ELEMENT ATTRTYPE (#PCDATA)>
	<!ELEMENT ATTRCOMPUTATION (#PCDATA)>
	<!ELEMENT ATTRDEPENDSON (OID+)>
	<!ELEMENT OIDNAME (#PCDATA)>
	<!ELEMENT OIDINDEX (OIDINDEXNAME, OIDINDEXNUM)>
	<!ATTLIST OIDINDEX
	type (string | number) #REQUIRED
>
	<!ELEMENT OIDINDEXNAME (#PCDATA)>
	<!ELEMENT OIDINDEXNUM (#PCDATA)>
]>
<SNMPDATA>
	<ATTRSET platform="unix">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="kb">
				<OIDNAME>1.3.6.1.4.1.791.2.9.4.5.2.7.2.1.3</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>DISK</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME> THROUGHPUT</ATTRNAME>
			<ATTRTYPE> STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME>1.3.6.1.4.1.791.2.9.4.5.2.7.2.1.2</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>DISK</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>DSK_STATUS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	</ATTRSET>
  <ATTRSET platform="unixA2">
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="kb">
				<OIDNAME>  1.3.6.1.4.1.791.2.10.2.74.2.12.2.1.9</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>DISK</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME> THROUGHPUT</ATTRNAME>
			<ATTRTYPE> STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
		<ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME> 1.3.6.1.4.1.791.2.10.2.74.2.12.2.1.6</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>DISK</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>DSK_STATUS</ATTRNAME>
			<ATTRTYPE>STATS</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	    <ATTRINFO>
			<OID representedby="value" type="scalar" returns="number">
				<OIDNAME> 1.3.6.1.4.1.791.2.10.2.74.2.12.2.1.8</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>DISK</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>CLUSTER_TYPE</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	    <ATTRINFO>
			<OID representedby="value" type="scalar" returns="string">
				<OIDNAME> 1.3.6.1.4.1.791.2.10.2.74.2.12.2.1.7</OIDNAME>
				<OIDINDEX type="string">
					<OIDINDEXNAME>DISK</OIDINDEXNAME>
					<OIDINDEXNUM>1</OIDINDEXNUM>
				</OIDINDEX>
			</OID>
			<ATTRNAME>DESC_NAME</ATTRNAME>
			<ATTRTYPE>CONFIG</ATTRTYPE>
			<ATTRCOMPUTATION> ASIS </ATTRCOMPUTATION>
		</ATTRINFO>
	</ATTRSET>
 </SNMPDATA>
